"""Parse main.py console logs and plot Figure 1 style Model A results.

The log files are generated by commands like:
    python -u main.py --signal <beta> >> results_beta*.txt

Only complete Monte Carlo runs are used. A run is considered complete when the
last default method in main.py prints:
    run k, percentage of rejection: pwd perm k3 ...

For each beta, only the first 50 complete runs are kept.
"""

from __future__ import annotations

import csv
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = Path(__file__).resolve().parent
RUNS_PER_BETA = 50

METHODS = [
    ("Proposed", "proposed"),
    ("MMD-G", "mmd_g"),
    ("ED2", "ed2"),
    ("BG", "bg"),
    ("PW", "pw"),
]

RAW_COLUMNS = [
    "beta",
    "global_run",
    "source_file",
    "local_run",
    "proposed",
    "mmd_g",
    "ed2",
    "bg",
    "pw",
]

SUMMARY_COLUMNS = [
    "beta",
    "n_used",
    "proposed_rate",
    "mmd_g_rate",
    "ed2_rate",
    "bg_rate",
    "pw_rate",
    "note",
]


def read_text(path: Path) -> str:
    data = path.read_bytes()
    if not data:
        return ""
    if data.startswith(b"\xff\xfe") or data.startswith(b"\xfe\xff"):
        return data.decode("utf-16", errors="ignore")
    for encoding in ("utf-8", "utf-16", "gbk"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="ignore")


def beta_from_filename(path: Path) -> tuple[float, int, str]:
    match = re.match(r"^results_beta(.+?)(?:_(\d+))?\.txt$", path.name)
    if not match:
        raise ValueError(f"Cannot parse beta from filename: {path.name}")
    beta_text = match.group(1)
    run_part = int(match.group(2) or 0)
    return float(beta_text), run_part, beta_text


def cumulative_to_decisions(rates_by_run: dict[int, float], complete_runs: list[int]) -> dict[int, int]:
    decisions: dict[int, int] = {}
    prev_sum = 0
    for run_id in complete_runs:
        if run_id not in rates_by_run:
            raise ValueError(f"Missing cumulative rate for complete run {run_id}")
        cumulative_sum = int(round(rates_by_run[run_id] * (run_id + 1)))
        decision = cumulative_sum - prev_sum
        if decision not in (0, 1):
            raise ValueError(
                f"Recovered invalid decision={decision} at run={run_id}; "
                f"rate={rates_by_run[run_id]}, previous_sum={prev_sum}"
            )
        decisions[run_id] = decision
        prev_sum = cumulative_sum
    return decisions


def parse_one_file(path: Path) -> list[dict[str, Any]]:
    beta, _, _ = beta_from_filename(path)
    text = read_text(path)
    if not text:
        return []

    complete_runs = sorted(
        set(
            int(match)
            for match in re.findall(
                r"(?m)^run\s+(\d+),\s*percentage of rejection:\s*pwd perm k3", text
            )
        )
    )
    if not complete_runs:
        return []

    proposed_rates = {
        int(run): float(rate)
        for run, rate in re.findall(
            r"(?m)^run\s+(\d+),\s*percentage of rejection:\s*max-sliced wd with l0 sparsity\s+([0-9.eE+-]+)",
            text,
        )
    }
    perm_rates = {
        int(run): (float(mmd), float(ed2), float(bg))
        for run, mmd, ed2, bg in re.findall(
            r"run\s+(\d+),\s*percentage of rejection:\s*mmd\s+([0-9.eE+-]+)\s*,\s*edl1\s+[0-9.eE+-]+,\s*edl2\s+([0-9.eE+-]+),\s*bg\s+([0-9.eE+-]+)",
            text,
            flags=re.S,
        )
    }
    pw_rates = {
        int(run): float(rate)
        for run, rate in re.findall(
            r"(?m)^run\s+(\d+),\s*percentage of rejection:\s*pwd perm k3\s+([0-9.eE+-]+)",
            text,
        )
    }

    mmd_rates = {run: values[0] for run, values in perm_rates.items()}
    ed2_rates = {run: values[1] for run, values in perm_rates.items()}
    bg_rates = {run: values[2] for run, values in perm_rates.items()}

    decisions_by_method = {
        "proposed": cumulative_to_decisions(proposed_rates, complete_runs),
        "mmd_g": cumulative_to_decisions(mmd_rates, complete_runs),
        "ed2": cumulative_to_decisions(ed2_rates, complete_runs),
        "bg": cumulative_to_decisions(bg_rates, complete_runs),
        "pw": cumulative_to_decisions(pw_rates, complete_runs),
    }

    rows: list[dict[str, Any]] = []
    for run_id in complete_runs:
        row = {
            "beta": beta,
            "source_file": path.name,
            "local_run": run_id,
        }
        for _, key in METHODS:
            row[key] = decisions_by_method[key][run_id]
        rows.append(row)
    return rows


def collect_first50() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    grouped: dict[float, list[dict[str, Any]]] = defaultdict(list)
    files = sorted(ROOT.glob("results_beta*.txt"), key=lambda p: beta_from_filename(p)[:2])
    for path in files:
        if path.name == "results_beta0.8txt":
            continue
        for row in parse_one_file(path):
            grouped[float(row["beta"])].append(row)

    raw_rows: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []
    for beta in sorted(grouped):
        rows = grouped[beta]
        if len(rows) < RUNS_PER_BETA:
            raise RuntimeError(f"beta={beta:g} has only {len(rows)} complete runs; need {RUNS_PER_BETA}.")

        selected = rows[:RUNS_PER_BETA]
        for index, row in enumerate(selected, start=1):
            out = dict(row)
            out["global_run"] = index
            raw_rows.append(out)

        summary = {
            "beta": beta,
            "n_used": RUNS_PER_BETA,
            "note": (
                "MMD-L is not plotted because main.py logs do not print lapmmd_decision; "
                "only logged methods are summarized."
            ),
        }
        for _, key in METHODS:
            summary[f"{key}_rate"] = sum(int(row[key]) for row in selected) / RUNS_PER_BETA
        summary_rows.append(summary)

    return raw_rows, summary_rows


def write_csv(path: Path, rows: list[dict[str, Any]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows({column: row.get(column, "") for column in columns} for row in rows)


def plot_summary(summary_rows: list[dict[str, Any]]) -> tuple[Path, Path]:
    betas = [float(row["beta"]) for row in summary_rows]
    styles = {
        "Proposed": {"color": "black", "marker": "o", "linestyle": "-"},
        "MMD-G": {"color": "#d62728", "marker": "s", "linestyle": "--"},
        "ED2": {"color": "#2ca02c", "marker": "^", "linestyle": "-."},
        "BG": {"color": "#9467bd", "marker": "D", "linestyle": ":"},
        "PW": {"color": "#1f77b4", "marker": "v", "linestyle": "-"},
    }

    fig, ax = plt.subplots(figsize=(7.2, 5.0), dpi=180)
    for label, key in METHODS:
        rates = [float(row[f"{key}_rate"]) for row in summary_rows]
        ax.plot(
            betas,
            rates,
            linewidth=2.0,
            markersize=6,
            label=label,
            **styles[label],
        )

    ax.set_title("Model A", fontsize=13)
    ax.set_xlabel(r"$\\beta$", fontsize=12)
    ax.set_ylabel("Empirical rejection rate", fontsize=12)
    ax.set_xticks(betas)
    ax.set_ylim(-0.02, 1.02)
    ax.grid(True, color="#d0d0d0", linewidth=0.7, alpha=0.75)
    ax.legend(frameon=False, ncol=2)
    fig.tight_layout()

    png_path = OUT_DIR / "Figure1_ModelA_first50.png"
    pdf_path = OUT_DIR / "Figure1_ModelA_first50.pdf"
    fig.savefig(png_path, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")
    plt.close(fig)
    return png_path, pdf_path


def main() -> None:
    raw_rows, summary_rows = collect_first50()
    write_csv(OUT_DIR / "modelA_first50_decisions.csv", raw_rows, RAW_COLUMNS)
    write_csv(OUT_DIR / "modelA_first50_summary.csv", summary_rows, SUMMARY_COLUMNS)
    png_path, pdf_path = plot_summary(summary_rows)

    print("Summary:")
    for row in summary_rows:
        print(
            f"beta={float(row['beta']):g}, n={row['n_used']}, "
            f"Proposed={row['proposed_rate']:.3f}, MMD-G={row['mmd_g_rate']:.3f}, "
            f"ED2={row['ed2_rate']:.3f}, BG={row['bg_rate']:.3f}, PW={row['pw_rate']:.3f}"
        )
    print(f"Saved: {OUT_DIR / 'modelA_first50_decisions.csv'}")
    print(f"Saved: {OUT_DIR / 'modelA_first50_summary.csv'}")
    print(f"Saved: {png_path}")
    print(f"Saved: {pdf_path}")


if __name__ == "__main__":
    main()
