"""Plot Fig. 2-style QQ plots for the GBM real-data analysis.

The script reads:
  - GBM/GBM_prognostic_low.txt
  - GBM/GBM_prognostic_high.txt
  - GBM/idx_genes_*.txt
  - GBM/direction_*.txt

The direction files are generated by running GBM_methylation.py first.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[1]
GBM_DIR = ROOT / "GBM"
OUT_DIR = Path(__file__).resolve().parent

FIG2_GENE_SETS = [
    ("mitotic_cell_cycle", "Mitotic cell cycle"),
    ("cell_cycle_process", "Cell cycle process"),
    ("cell_cycle", "Cell cycle"),
    ("DNA_metabolic_process", "DNA metabolic process"),
    ("cell_division", "Cell division"),
    ("mitotic_nuclear_division", "Mitotic nuclear division"),
]


def load_vector(path: Path) -> np.ndarray:
    values = np.loadtxt(path)
    return np.atleast_1d(values).astype(float).reshape(-1)


def load_indices(path: Path) -> np.ndarray:
    # The index files were written by R, so they are 1-based.
    return np.atleast_1d(np.loadtxt(path)).astype(int).reshape(-1) - 1


def project_group(data: np.ndarray, idx: np.ndarray, direction: np.ndarray) -> np.ndarray:
    if direction.size == idx.size:
        return data[:, idx] @ direction
    if direction.size == data.shape[1]:
        return data @ direction
    raise ValueError(
        "Direction length does not match either the gene-set size or the full data dimension: "
        f"direction={direction.size}, gene_set={idx.size}, full_dim={data.shape[1]}"
    )


def orient_projection(lgg_proj: np.ndarray, gbm_proj: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Fix the arbitrary sign of the projection for more stable visual output."""
    if np.median(gbm_proj) < np.median(lgg_proj):
        return -lgg_proj, -gbm_proj
    return lgg_proj, gbm_proj


def qq_points(lgg_proj: np.ndarray, gbm_proj: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    probs = np.linspace(0.01, 0.99, 99)
    return np.quantile(lgg_proj, probs), np.quantile(gbm_proj, probs)


def make_figure(data_lgg: np.ndarray, data_gbm: np.ndarray, orient_by_median: bool) -> plt.Figure:
    title = "QQ plots of projected methylation distributions"
    if orient_by_median:
        title += " (median-oriented)"

    fig, axes = plt.subplots(2, 3, figsize=(12, 7.4), constrained_layout=True)
    axes = axes.reshape(-1)

    for ax, (key, title_text) in zip(axes, FIG2_GENE_SETS):
        idx_path = GBM_DIR / f"idx_genes_{key}.txt"
        direction_path = GBM_DIR / f"direction_{key}.txt"
        if not direction_path.exists():
            raise FileNotFoundError(
                f"Missing {direction_path}. Run `python GBM_methylation.py` first."
            )

        idx = load_indices(idx_path)
        direction = load_vector(direction_path)
        lgg_proj = project_group(data_lgg, idx, direction)
        gbm_proj = project_group(data_gbm, idx, direction)
        if orient_by_median:
            lgg_proj, gbm_proj = orient_projection(lgg_proj, gbm_proj)
        xq, yq = qq_points(lgg_proj, gbm_proj)

        axis_min = min(xq.min(), yq.min())
        axis_max = max(xq.max(), yq.max())
        padding = 0.06 * (axis_max - axis_min)
        axis_min -= padding
        axis_max += padding

        ax.plot(xq, yq, color="#1f77b4", linewidth=1.8)
        ax.scatter(xq, yq, s=10, color="#1f77b4", alpha=0.75)
        ax.plot([axis_min, axis_max], [axis_min, axis_max], "--", color="0.35", linewidth=1.1)
        ax.set_xlim(axis_min, axis_max)
        ax.set_ylim(axis_min, axis_max)
        ax.set_title(title_text, fontsize=12)
        ax.set_xlabel("Quantiles (LGG)")
        ax.set_ylabel("Quantiles (GBM)")
        ax.grid(True, color="0.88", linewidth=0.7)

    fig.suptitle(title, fontsize=14)
    return fig


def save_figure(fig: plt.Figure, stem: str) -> None:
    png_path = OUT_DIR / f"{stem}.png"
    pdf_path = OUT_DIR / f"{stem}.pdf"
    fig.savefig(png_path, dpi=300)
    fig.savefig(pdf_path)
    plt.close(fig)

    print(f"Saved PNG: {png_path}")
    print(f"Saved PDF: {pdf_path}")


def main() -> None:
    low_path = GBM_DIR / "GBM_prognostic_low.txt"
    high_path = GBM_DIR / "GBM_prognostic_high.txt"
    if not low_path.exists() or not high_path.exists():
        raise FileNotFoundError(
            "Cannot find GBM data files. Run this script from the repository after data are prepared."
        )

    data_lgg = np.loadtxt(low_path)
    data_gbm = np.loadtxt(high_path)

    save_figure(make_figure(data_lgg, data_gbm, orient_by_median=False), "Figure2_QQ_GBM_final")
    save_figure(make_figure(data_lgg, data_gbm, orient_by_median=True), "Figure2_QQ_GBM_median_oriented_final")


if __name__ == "__main__":
    main()
